(exception_type $b)(func try $try catch $b rethrow $try rethrow $try)