(exception_type $b)(func rethrow $$ rethrow $try rethrow $tr rethrow $tr$ r$t.y)