(exception_type $b)(func $b rethrow $try rethrow $try rethrow $try rethrow  $trytry rethrow $try rethrow  $try rethrow $try rethrow $try rethrow $try rethrow $try rethrow $try rethrow $try rethrow $tryry rethrow $try rethrow $try rethrow $try rethrow $try rethrow $try rethrow $t rethrow $try rethrow $try rethrow $try rethrow $try rethrow $try rethrow $try rethrow $tryry rethrow $try rethrow $try rethrow $try rethrow $try rethrow $try rethrow $try y )