(module(exception_type $b ) (func(result i32) try $try(result i32)
i32.const 2 catch $b  rethrow $try 
end ))